spring:
  # aj-captcha 对redis缓存的依赖。
  redis:
    database: 2
    host: 192.168.23.132
    port: 6379
    password: ''
    timeout: 60000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
          # 数据库链接 [主数据源]
      main:
        #url: jdbc:mysql://rm-2vc18hy5e4390e099oo.mysql.cn-chengdu.rds.aliyuncs.com:3306/zzdemo-multi?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
        #username: dev
        #password: Asdf3211
        url: jdbc:mysql://localhost:3306/charge_system?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      # 默认生成的操作日志数据源配置，缺省情况下和工程中配置的upms数据库链接一致，可根据需求自行修改。
      operation-log:
        url: jdbc:mysql://localhost:3306/charge_system?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      name: application-webadmin
      initialSize: 10
      minIdle: 10
      maxActive: 50
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      maxOpenPreparedStatements: 20
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      filters: stat,wall
      useGlobalDataSourceStat: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*,/actuator/*"
      stat-view-servlet:
        enabled: true
        urlPattern: /druid/*
        resetEnable: true
application:
  # Jwt令牌加密的签名值。该值的长度要超过10个字符(过短会报错)。
  tokenSigningKey: courseEvaluate-signing-key
  # Jwt令牌在Http Header中的键名称。
  tokenHeaderKey: Authorization
  # Jwt令牌刷新后在Http Header中的键名称。
  refreshedTokenHeaderKey: RefreshedToken
  # Jwt令牌过期时间(毫秒)。
  expiration: 72000000
  # 初始化密码。
  defaultUserPassword: 123456
  # 缺省的文件上传根目录。
  uploadFileBaseDir: ./zz-resource/upload-files/app
  # 跨域的IP(http://192.168.10.10:8086)白名单列表，多个IP之间逗号分隔(* 表示全部信任，空白表示禁用跨域信任)。
  credentialIpList: "*"
  # Session的用户和数据权限在Redis中的过期时间(秒)。
  sessionExpiredSeconds: 86400

# 这里仅仅是一个第三方配置的示例，如果没有接入斯三方系统，
# 这里的配置项也不会影响到系统的行为，如果觉得多余，也可以手动删除。
third-party:
  # 第三方系统接入的用户鉴权配置。
  auth:
  - appCode: orange-forms-default
    # 访问第三方系统接口的URL前缀，橙单会根据功能添加接口路径的其余部分，
    # 比如获取用户Token的接口 http://localhost:8083/orangePluginTest/getTokenData
    baseUrl: http://localhost:8083/orangePlugin
    # 第三方返回的用户Token数据的缓存过期时长，单位秒。
    # 如果为0，则不缓存，每次涉及第三方的请求，都会发出http请求，交由第三方验证，这样对系统性能会有影响。
    tokenExpiredSeconds: 60
    # 第三方返回的权限数据的缓存过期时长，单位秒。
    permExpiredSeconds: 86400

# 这里仅仅是一个第三方配置的示例，如果没有接入斯三方系统，
# 这里的配置项也不会影响到系统的行为，如果觉得多余，也可以手动删除。
common-ext:
  # 这里可以配置多个第三方应用，这里的应用数量，通常会和上面third-party.auth的配置数量一致。
  apps:
    # 应用唯一编码，尽量不要使用中文。
  - appCode: orange-forms-default
    # 业务组件的数据源配置。
    bizWidgetDatasources:
    # 组件的类型，多个类型之间可以逗号分隔。
    - types: upms_user,upms_dept
      # 组件获取列表数据的接口地址。
      listUrl: http://localhost:8083/orangePlugin/listBizWidgetData
      # 组件获取详情数据的接口地址。
      viewUrl: http://localhost:8083/orangePlugin/viewBizWidgetData

sequence:
  # Snowflake 分布式Id生成算法所需的WorkNode参数值。
  snowflakeWorkNode: 1
# 存储session数据的Redis，所有服务均需要，因此放到公共配置中。
# 根据实际情况，该Redis也可以用于存储其他数据。
redis:
  # redisson的配置。每个服务可以自己的配置文件中覆盖此选项。
  redisson:
    # 如果该值为false，系统将不会创建RedissionClient的bean。
    enabled: true
    # mode的可用值为，single/cluster/sentinel/master-slave
    mode: single
    # single: 单机模式
    #   address: redis://localhost:6379
    # cluster: 集群模式
    #   每个节点逗号分隔，同时每个节点前必须以redis://开头。
    #   address: redis://localhost:6379,redis://localhost:6378,...
    # sentinel:
    #   每个节点逗号分隔，同时每个节点前必须以redis://开头。
    #   address: redis://localhost:6379,redis://localhost:6378,...
    # master-slave:
    #   每个节点逗号分隔，第一个为主节点，其余为从节点。同时每个节点前必须以redis://开头。
    #   address: redis://localhost:6379,redis://localhost:6378,...
    address: redis://192.168.23.132:6379
    # 链接超时，单位毫秒。
    timeout: 6000
    # 单位毫秒。分布式锁的超时检测时长。
    # 如果一次锁内操作超该毫秒数，或在释放锁之前异常退出，Redis会在该时长之后主动删除该锁使用的key。
    lockWatchdogTimeout: 60000
    # redis 密码，空可以不填。
    password: 123456
    pool:
      # 连接池数量。
      poolSize: 20
      # 连接池中最小空闲数量。
      minIdle: 5
minio:
  enabled: false
  endpoint: http://10.168.136.185:9000
  accessKey: admin
  secretKey: p@ssw0rd
  bucketName: gae-middleground-contract
